title: Access Denied
description: Технические задачи, за которые обычно никто не берётся. Реверс, моддинг, исследовательские проекты, прототипы.
url: "https://nbv000.su"
baseurl: ""
author: nbv000
contact_channel: accses_denied
lang: ru_RU

twitter:
  card: summary_large_image

markdown: kramdown
permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-image.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
